services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres.hpzmwbctmctagutqgjpf:Casa43515134@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - DIRECT_URL=postgresql://postgres.hpzmwbctmctagutqgjpf:Casa43515134@aws-0-us-east-1.pooler.supabase.com:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 