version: '3.8'

networks:
  rcf_network:
    name: rcf_network

services:
  server:
    container_name: rcf_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3501:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres.hpzmwbctmctagutqgjpf:Casa43515134@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - DIRECT_URL=postgresql://postgres.hpzmwbctmctagutqgjpf:Casa43515134@aws-0-us-east-1.pooler.supabase.com:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=https://rcfapp.com.ar
      - BASE_PATH=/rcf/api
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - rcf_network
    labels:
      - "project=rcf"
      - "environment=production"
    restart: unless-stopped 