version: '3.8'

services:
  app:
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  client:
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development