// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC63HcJiZPxNDxCSwFm0258ctV0ILQDjRc',
    appId: '1:12092366512:web:4322f9e05508567035a575',
    messagingSenderId: '12092366512',
    projectId: 'rfc-app-11121',
    authDomain: 'rfc-app-11121.firebaseapp.com',
    storageBucket: 'rfc-app-11121.firebasestorage.app',
    measurementId: 'G-4XD97Z168J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzQe6juCp_P--6CyC63u68Yrl2DXbWco',
    appId: '1:12092366512:android:e980e60ed0b2738f35a575',
    messagingSenderId: '12092366512',
    projectId: 'rfc-app-11121',
    storageBucket: 'rfc-app-11121.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn7SEX5nlD_E2MdrnqJQbffYdXvhKOA4c',
    appId: '1:12092366512:ios:27946468a70c833735a575',
    messagingSenderId: '12092366512',
    projectId: 'rfc-app-11121',
    storageBucket: 'rfc-app-11121.firebasestorage.app',
    iosClientId: '12092366512-q8j5fa77urjka00vj25eqvie1v8mqmgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn7SEX5nlD_E2MdrnqJQbffYdXvhKOA4c',
    appId: '1:12092366512:ios:27946468a70c833735a575',
    messagingSenderId: '12092366512',
    projectId: 'rfc-app-11121',
    storageBucket: 'rfc-app-11121.firebasestorage.app',
    iosClientId: '12092366512-q8j5fa77urjka00vj25eqvie1v8mqmgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_sC2GVuONYa3E0Nn9_ID9buZcRWAvVHw',
    appId: '1:12092366512:web:e2495e78d05746fc35a575',
    messagingSenderId: '12092366512',
    projectId: 'rfc-app-11121',
    authDomain: 'rfc-app-11121.firebaseapp.com',
    storageBucket: 'rfc-app-11121.firebasestorage.app',
    measurementId: 'G-VW69Q6VQ4K',
  );
}
